name: Trivy Scan

on:
  push:
    branches:
      - main  # Replace 'main' with your default branch name

jobs:
  trivy_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t your-image-name:latest .

      - name: Run Trivy scan
        run: |
          docker pull your-image-name:latest
          docker run --rm -v $(pwd):/workdir aquasec/trivy your-image-name:latest
