name: trivy

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  schedule:
    - cron: '29 19 * * 0'

permissions:
  contents: read

jobs:
  build:
    permissions:
      contents: read
      security-events: write
      actions: read
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Trufflehog secret scanner
        run: |
          pip install trufflehog
          pip install joern2sarif
          trufflehog --regex --entropy=False --json . > trufflehog-results.json

      - name: Convert findings to SARIF format
        run: |
          pip install joern2sarif
          joern2sarif -i trufflehog-results.json -o trufflehog-findings.sarif

      - name: Upload Trufflehog scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'trufflehog-results.sarif'
