name: Semgrep Code Scanning

on:
  push:
    branches:
      - main

jobs:
  semgrep:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Semgrep
        run: |
          pip install semgrep

      - name: Run Semgrep
        run: |
          semgrep --config my_rules.yaml /path/to/your/code > results.txt

      - name: Upload Semgrep results as code scanning alerts
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: results.txt
