name: trivy

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  schedule:
    - cron: '29 19 * * 0'

permissions:
  contents: read

jobs:
  build:
    permissions:
      contents: read
      security-events: write
      actions: read
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: clone application source code
        uses: actions/checkout@v3
        with:
          path: ./code
    
      #step3: Install Semgrep
      - name: Install Semgrep
        run: |
          python -m pip install --upgrade pip
          python3 -m pip install semgrep
      
      #step4: Code scan
      - name: Scan
        env:
          SEMGREP_RULES_PATH: ./SemgrepRules
        run: |
          python -m semgrep --config --config auto . --output $(date +"%d-%m-%Y").json --json > scanSummry.txt 2>&1

      #step5: get current date  
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%d-%m-%Y')"

      #step6: Push report to artifact.
      - name: save report as pipeline artifact
        uses: actions/upload-artifact@v3
        with:
            name: ${{ steps.date.outputs.date }}.json
            path: .
